name: Android CI

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  ANDROID_NDK_HOME: $GITHUB_WORKSPACE/toolchains/android-ndk-r26-beta2

jobs:
  android-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Setup ninja
        uses: abdes/gha-setup-ninja@master

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run all
        run: |
          bash ./platforms/build-android.sh
          cp -r ./assets/ platforms/android/app/src/main

      - name: Build APK
        run: | 
          cd platforms/android/
          ./gradlew bundelDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: oopetris.aab
          path: platforms/android/app/build/outputs/bundle/debug/app-debug.aab
