name: Android CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    android-build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "0"

            - name: Install Android Tools
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt install curl pkg-config zip unzip tar git openjdk-19-jdk ant android-sdk-platform-tools-common -y
                  mkdir toolchains

            - name: Install Android NDK
              uses: ravinderjangra/android-ndk-toolchain-setup@0.2
              with:
                api: '33'
                arch: 'x86'
                install-location: 'toolchains'
                force: true

            - name: Setup Android SDK
              uses: android-actions/setup-android@v2

            - name: Install cmake >= 3.25
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install gpg wget
                  wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
                  echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
                  sudo apt-get update
                  sudo apt-get install cmake -y

            - name: Install vcpkg
              shell: bash
              run: |
                  cd "${{github.workspace}}"
                  git clone https://github.com/Microsoft/vcpkg.git
                  "${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh"

            - uses: seanmiddleditch/gha-setup-ninja@master

            - name: Configure CMake
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.config.buildtype }} -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake" ${{github.workspace}} -G Ninja

            - name: Build
              # Build your program with the given configuration
              run: cmake --build ${{github.workspace}}/build -j --config ${{ matrix.config.buildtype }}

          
            - name: Upload artifacts - Android
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.config.name }} Executable
                  path: build/${{ matrix.config.buildtype }}\oopetris.apk
