name: Android CI

on:
    push:
        branches: ["main"]
    pull_request:
    workflow_dispatch:

jobs:
    android-build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "0"

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip
                  pip install meson

            - name: Setup ninja
              uses: seanmiddleditch/gha-setup-ninja@master

            - name: Run all
              run: |
                  bash ./platforms/build-android.sh
                  cp -r ./assets/ platforms/android/app/src/main

            - name: Build APK
              uses: sparkfabrik/android-build-action@v1.3.4
              with:
                  build-type: assemble
                  gradle-task: assembleDebug
                  project-path: platforms/android
                  output-path: oopetris.apk

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: oopetris.apk
                  path: oopetris.apk
