name: Android CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    android-build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "0"

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip
                  pip install meson

            - name: Setup ninja
              uses: seanmiddleditch/gha-setup-ninja@master

            - name: Run all
              run: bash ./android/run.sh

          
            - name: Upload artifacts - Android
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.config.name }} Executable
                  path: build/${{ matrix.config.buildtype }}\oopetris.apk
