name: Android CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    android-build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "0"

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip
                  pip install meson

            - name: Setup ninja
              uses: seanmiddleditch/gha-setup-ninja@master

            - name: Run all
              run: bash ./android/run.sh

            - name: Build and Upload apk
              uses: sparkfabrik/android-build-action@v1.3.4
              with:
                  build-type: assemble
                  gradle-task: assembleRelease
                  project-path: android/project
                  output-path: oopetris.apk
