name: c++ lints(clang-format + clang-tidy)
on: pull_request
jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          #TODO set this up: (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 14
          extra-args: -std=c++2b -Wall -Wextra -Wpedantic
          files-changed-only: false
          lines-changed-only: false

      - name: Fail CI run if linter checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1