name: C++ lints(clang-format + clang-tidy)
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 17
          platform: x64

      - name: Prepare compile_commands.json
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libsdl2-2.0-0 libsdl2-dev libsdl2-net* libsdl2-ttf* -y
          meson setup build -Dbuildtype=release

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 17
          database: build
          files-changed-only: ${{ github.event_name != 'workflow_dispatch' }}
          lines-changed-only: ${{ github.event_name != 'workflow_dispatch' }}
          thread-comments: true
          tidy-checks: ""
          file-annotations: true
          ignore: subprojects|build|android|assets|recordings|docs|toolchains|platforms

      - name: Fail CI run if linter checks failed
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "${{ steps.linter.outputs.checks-failed }} linter checks failed"
          exit 1
