name: C++ lints(clang-format + clang-tidy)
on: pull_request

jobs:
    cpp-linter:
        runs-on: ubuntu-22.04
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v3
            - uses: cpp-linter/cpp-linter-action@v2
              id: linter
              with:
                  style: file
                  version: 15
                  extra-args: -std=c++2b -Wall -Wextra -Wpedantic
                  files-changed-only: false
                  lines-changed-only: false
                  thread-comments: true
                  file-annotations: false
                  tidy-checks: "boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*"

            - name: Fail CI run if linter checks failed
              if: steps.linter.outputs.checks-failed > 0
              run: exit 1
