name: Flatpak build

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak build github.mgerhold.OOPetris"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: install flatpak
        run: | 
          sudo apt-get install dbus-daemon flatpak flatpak-builder git-lfs python3-aiohttp python3-tenacity xvfb ccache zstd libappstream-glib* -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          sudo flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
          sudo flatpak install -y --noninteractive flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
      - name: manual run
        run: | 
          mkdir -p repo
          flatpak-builder --user --disable-rofiles-fuse --force-clean --repo=./repo flatpak-build github.mgerhold.OOPetris.yml
          flatpak build-bundle ./repo oopetris.flatpak github.mgerhold.OOPetris
