name: Flatpak build

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak build"
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: get GPG key of repo
        run: |
          echo "TODO"

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.1
        with:
          cache-key: flatpak-builder-${{ github.sha }}
          bundle: oopetris.flatpak
          manifest-path: com.github.mgerhold.OOPetris.yml
          gpg-sign: F3B69A312966F5C3288171D1F3225A7952DF302D


      - uses: flatpak/flatpak-github-actions/flat-manager@v4
        name: "Deploy"
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}  
        with:
          repository: stable
          flat-manager-url: https://oopetris.totto.tk/repo
          token:  ${{ secrets.FLATPAK_REPO_TOKEN }}
          
