name: Flatpak build

on:
  release:
    types: [published]
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: 'Flatpak build'
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: oopetris.flatpak
          manifest-path: io.github.openbrickprotocolfoundation.oopetris.yml
          verbose: ${{ runner.debug == '1' && 'true' || 'false' }}
