name: Flatpak CI

on:
  release:
    types: [published]
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak build (${{ matrix.config.arch }})
    runs-on: ubuntu-${{ matrix.config.os-version }}
    strategy:
      matrix:
        config:
          - arch: x86_64
            os-version: 24.04

          - arch: aarch64
            os-version: 24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: oopetris.flatpak
          manifest-path: io.github.openbrickprotocolfoundation.oopetris.yml
          verbose: ${{ runner.debug == '1' && 'true' || 'false' }}
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.config.arch }}

      - uses: flatpak/flatpak-github-actions/flat-manager@v6
        name: 'Deploy'
        if: github.event_name != 'pull_request'
        with:
          repository: beta
          flat-manager-url: http://flat-man.oopetris.totto.lt
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}
