name: Flatpak build

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak build github.mgerhold.OOPetris"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: oopetris.flatpak
          manifest-path: github.mgerhold.OOPetris.yml
          run-tests: false
          verbose: true
