name: Test CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run Tests 
    runs-on: ubuntu-22.
    strategy:
      fail-fast: false
      matrix:
        # Customize the Meson build type here ("plain", "debug", "debugoptimized", "release", "minsize", "custom".)
        config:
          - name: Test Release 
            buildtype: release

          - name: Test Debug 
            buildtype: debug

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup GCC 
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13
          platform: x64
  
      - name: Setup meson
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libsdl2-2.0-0 libsdl2-dev libsdl2-ttf* libsdl2-mixer* libsdl2-image* -y


      - name: Configure
        run: meson setup build -Dbuildtype=${{ matrix.config.buildtype }} -Db_coverage=true -Dtests=true

      - name: Build
        run: meson compile -C build 

      - name: Coverage
        run: ninja coverage-xml -C build


      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "build/meson-logs/coverage.xml"
          threshold_metric: "lines"

      - name: Upload test coverage artifacts
        uses: actions/upload-artifact@v4
        with:
            name: Tests coverage artifacts
            path: build/meson-logs/coverage.xml
