name: Windows Installer CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  installer:
    name: Windows MSVC Installer
    runs-on: windows-2022

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup MSVC (Windows)
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          toolset: '14.41'

      - name: Setup meson
        run: |
          pip install meson

      - name: Download EnVar plugin for NSIS
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}

      - name: Extract EnVar plugin
        run: 7z x "-oC:/Program Files (x86)/NSIS" "${{ github.workspace }}/envar_plugin.zip"

      - name: Configure
        run: meson setup build -Dbuildtype=release -Ddefault_library=shared -Dbuild_installer=true

      - name: Build installer
        run: |
          meson compile -C build
          meson install -C build --tags runtime --destdir "dynamic_libraries" 
          meson compile -C build windows_installer

      - name: Upload artifacts - Windows
        uses: actions/upload-artifact@v4
        with:
          name: OOpetris Setup
          path: tools/installer/OOPetris Setup.exe
