name: Windows Installer CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  installer:
    name: Windows MSVC Installer
    runs-on: windows-2025
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup MSVC (Windows)
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          toolset: '14.43'

      - name: Setup meson
        run: |
          pip install meson

      - name: Install NSIS with EnVar plugin
        uses: repolevedavaj/install-nsis@v1.0.1
        with:
          nsis-version: '3.11'

      - name: Configure
        run: meson setup build -Dbuildtype=release -Ddefault_library=shared -Dbuild_installer=true -Drun_in_ci=true
        # TODO: enable fatal warnings, once cpp-httplib is patched either by ourselves or by the maintainers: --fatal-meson-warnings

      - name: Build installer
        run: |
          meson compile -C build
          meson install -C build --tags runtime --destdir "dynamic_libraries" 
          meson compile -C build windows_installer

      - name: Upload artifacts - Windows
        uses: actions/upload-artifact@v4
        with:
          name: OOpetris Setup
          path: tools/installer/OOPetris Setup.exe
